export const MOCK_DOCTOR = {
  id: "mock-doctor-1",
  full_name: "Dr. Udatta Chowdhury",
  phone: "9876543210",
  referral_link: "https://habuild.in/udatta-wellness-program",
};

export const MOCK_PATIENTS = [
  {
    id: "1",
    name: "Rishi Kapoor",
    mobile: "9876543210",
    notes: "Diabetic, morning yoga recommended",
    lastPrescriptionDate: "2026-06-10",
    prescriptionCount: 3,
  },
  {
    id: "2",
    name: "Ananya Verma",
    mobile: "8765432109",
    notes: "High BP, stress management focus",
    lastPrescriptionDate: "2026-06-08",
    prescriptionCount: 2,
  },
  {
    id: "3",
    name: "Rohan Patel",
    mobile: "7654321098",
    notes: "Weight management program",
    lastPrescriptionDate: "2026-06-12",
    prescriptionCount: 5,
  },
  {
    id: "4",
    name: "Priya Singh",
    mobile: "6543210987",
    notes: "Post-operative recovery",
    lastPrescriptionDate: "2026-06-05",
    prescriptionCount: 1,
  },
  {
    id: "5",
    name: "Amit Kumar",
    mobile: "5432109876",
    notes: "Sleep disorder treatment",
    lastPrescriptionDate: "2026-06-11",
    prescriptionCount: 4,
  },
  {
    id: "6",
    name: "Sneha Dutta",
    mobile: "4321098765",
    notes: "Anxiety management",
    lastPrescriptionDate: "2026-06-09",
    prescriptionCount: 2,
  },
];

export const MOCK_PRESCRIPTIONS = [
  {
    id: "1",
    patientName: "Rishi Kapoor",
    patientMobile: "9876543210",
    habits: ["10 minutes Yoga", "Sleep before 11 PM", "Drink 2 litres water"],
    createdAt: "2026-06-10",
    status: "sent",
  },
  {
    id: "2",
    patientName: "Ananya Verma",
    patientMobile: "8765432109",
    habits: ["5 minutes Deep Breathing", "15 minutes Walking", "Avoid screen before bed"],
    createdAt: "2026-06-08",
    status: "sent",
  },
  {
    id: "3",
    patientName: "Rohan Patel",
    patientMobile: "7654321098",
    habits: ["10 minutes Meditation", "Eat fruits daily", "Drink 2 litres water"],
    createdAt: "2026-06-12",
    status: "sent",
  },
  {
    id: "4",
    patientName: "Rishi Kapoor",
    patientMobile: "9876543210",
    habits: ["10 minutes Yoga"],
    createdAt: "2026-06-05",
    status: "sent",
  },
  {
    id: "5",
    patientName: "Priya Singh",
    patientMobile: "6543210987",
    habits: ["15 minutes Walking", "Sleep before 11 PM"],
    createdAt: "2026-06-05",
    status: "sent",
  },
  {
    id: "6",
    patientName: "Amit Kumar",
    patientMobile: "5432109876",
    habits: ["10 minutes Meditation", "Sleep before 11 PM", "Avoid screen before bed"],
    createdAt: "2026-06-11",
    status: "sent",
  },
  {
    id: "7",
    patientName: "Sneha Dutta",
    patientMobile: "4321098765",
    habits: ["5 minutes Deep Breathing", "10 minutes Meditation"],
    createdAt: "2026-06-09",
    status: "sent",
  },
  {
    id: "8",
    patientName: "Rohan Patel",
    patientMobile: "7654321098",
    habits: ["15 minutes Walking", "Eat fruits daily"],
    createdAt: "2026-06-02",
    status: "sent",
  },
  {
    id: "9",
    patientName: "Ananya Verma",
    patientMobile: "8765432109",
    habits: ["10 minutes Yoga", "Drink 2 litres water"],
    createdAt: "2026-05-28",
    status: "sent",
  },
  {
    id: "10",
    patientName: "Amit Kumar",
    patientMobile: "5432109876",
    habits: ["Sleep before 11 PM"],
    createdAt: "2026-05-25",
    status: "sent",
  },
];

export const MOCK_ANALYTICS = {
  totalSent: 47,
  totalPatients: 6,
  thisMonth: 12,
  dailyData: [
    { date: "Jun 01", count: 1 },
    { date: "Jun 02", count: 2 },
    { date: "Jun 03", count: 0 },
    { date: "Jun 04", count: 1 },
    { date: "Jun 05", count: 3 },
    { date: "Jun 06", count: 0 },
    { date: "Jun 07", count: 1 },
    { date: "Jun 08", count: 2 },
    { date: "Jun 09", count: 1 },
    { date: "Jun 10", count: 2 },
    { date: "Jun 11", count: 2 },
    { date: "Jun 12", count: 1 },
    { date: "Jun 13", count: 0 },
    { date: "Jun 14", count: 0 },
    { date: "Jun 15", count: 0 },
  ],
  habitCounts: [
    { name: "Sleep before 11 PM", count: 8 },
    { name: "10 minutes Yoga", count: 6 },
    { name: "Drink 2 litres water", count: 5 },
    { name: "15 minutes Walking", count: 5 },
    { name: "10 minutes Meditation", count: 5 },
    { name: "5 minutes Deep Breathing", count: 3 },
    { name: "Avoid screen before bed", count: 2 },
    { name: "Eat fruits daily", count: 2 },
  ],
};
